name: Compile Test

on:
  push:
    branches-ignore: 
      - master
      - 'feature/**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/.gitignore'
      - '**/README.md'
      - .github/**
      - .tgitconfig
      - 'Release Notes.txt'

  pull_request:
    branches:
      - master
      - 'feature/**'
    paths-ignore:
      - '**/.gitignore'
      - '**/README.md'
      - .github/**
      - .tgitconfig
      - 'Release Notes.txt'
    

jobs:

  compile_test:
  
    runs-on: windows-2025-vs2026

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Display dotnet version
        run: dotnet --version
          
      - uses: microsoft/setup-msbuild@v2
      
      - name: Build Release
        run: msbuild Vixen.sln -m -t:restore -t:Rebuild -p:Configuration=Release
  
      - run: dir
        shell: cmd
